INSERT INTO AUTHORITY (name) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (name) VALUES ('ROLE_SYS_ADMIN');
INSERT INTO AUTHORITY (name) VALUES ('ROLE_AIRCOMPANY_ADMIN');
INSERT INTO AUTHORITY (name) VALUES ('ROLE_HOTEL_ADMIN');
INSERT INTO AUTHORITY (name) VALUES ('ROLE_RENTACAR_ADMIN');